name = "marked/rubine"
version = "0.3.0-alpha.0"
description = "An ergonomic, runtime agnostic scheduler for jecs"
authors = ["marked"]
repository = "https://github.com/mark-marks/rubine"
license = "MIT"
includes = ["lib", "LICENSE", "pesde.toml", "README.md", "DESIGN.md", "CHANGELOG.md", ".luaurc"]

[target]
environment = "luau"
lib = "lib/init.luau"

[indices]
default = "https://github.com/pesde-pkg/index"

[dependencies]
jecs = { name = "marked/jecs", version = "^0.11.0" }
