name = "mark_marks/rubine"
version = "0.2.0"
description = "An ergonomic, runtime agnostic scheduler for jecs"
authors = ["marked/Mark-Marks"]
repository = "https://github.com/mark-marks/rubine"
license = "MIT"
includes = ["lib", "LICENSE", "pesde.toml", "README.md", ".luaurc"]

[target]
environment = "luau"
lib = "lib/init.luau"

[indices]
default = "https://github.com/daimond113/pesde-index"

[wally_indices]
default = "https://github.com/UpliftGames/wally-index"

[dependencies]
jecs = { name = "mark_marks/jecs_pesde", version = "^0.5.3" }

# I don't want to keep a separate installation of wally packages for extensions
[dev_dependencies]
jabby = { wally = "alicesaidhi/jabby", version = "0.2.0-rc.5" }
