[package]
name = "mark-marks/rubine"
version = "0.3.0-alpha.1"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
license = "MIT"
exclude = ["**"]
include = [
    "default.project.json",
    "lib",
    "lib/**",
    "LICENSE",
    "wally.toml",
    "README.md",
    "DESIGN.md",
    "CHANGELOG.md",
    ".luaurc",
    "jecs.luau"
]

[dependencies]
jecs = "ukendio/jecs@0.11.0"
