name: Release Rubine Roblox

on:
  push:
    tags: ["rbx-v*"]
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4

      - name: Install Rokit
        uses: CompeyDev/setup-rokit@v0.1.2
        with:
          token: ${{ SECRETS.GITHUB_TOKEN }}

      - name: Build
        run: |
          rojo sourcemap -o sourcemap.json
          rojo build -o build.rbxm

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: ./extensions/roblox/build.rbxm

  release:
    name: Release
    needs: [build]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4

      - name: Download Build
        uses: actions/download-artifact@v4
        with:
          name: build
          path: build

      - name: Rename Build
        run: mv build/build.rbxm rubine-roblox.rbxm

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name: Rubine Roblox ${{ github.ref_name }}
          files: |
            rubine-roblox.rbxm

  publish:
    name: Publish
    needs: [release]
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          registry-url: "https://registry.npmjs.org"

      - name: Install Rokit
        uses: CompeyDev/setup-rokit@v0.1.2
        with:
          token: ${{ SECRETS.GITHUB_TOKEN }}

      - name: Wally Login
        working-directory: ./extensions/roblox
        run: wally login --token ${{ secrets.WALLY_AUTH_TOKEN }}

      - name: Wally Publish
        working-directory: ./extensions/roblox
        run: wally publish

      - name: Install NPM Packages
        working-directory: ./extensions/roblox
        run: npm install

      - name: Add shims
        run: zune run scripts/shim

      - name: NPM Publish
        working-directory: ./extensions/roblox
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
